config/routes.rb
Rails.application.routes.draw do
 
  

  get 'sessions/new'

  get '/users' => 'users#index'
  get '/users/show' 
  get '/users/:id' => 'users#show'

  get '/about' => 'site#about'
  get '/contact' => 'site#contact' 
  get '/gallery' => 'site#gallery' 
  
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  get '/checkout' => 'cart#checkout'
  get '/thankyou' => 'cart#thankyou'
  
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  post 'logout'  => 'sessions#destroy' 

  resources :arts
  resources :users
  

  root 'arts#index'

end

app/models/art.rb
class Art < ActiveRecord::Base
    validates :art_id, presence: true
    validates :name, presence: true
    validates :description, presence: true
    validates :catagory, presence: true
    validates :size, presence: true
    validates :price, presence: true
    validates :url, presence: true
    
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]
  
  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:art_id, :name, :description, :catagory, :size, :price, :url)
    end
end

app/helpers/arts_helper.rb
module ArtsHelper
      
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
end

app/views/arts/_form.html.erb
<%= form_for(@art) do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :art_id %><br>
    <%= f.number_field :art_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :catagory %><br>
    <%= f.text_field :catagory %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing Art</h1>

<%= render 'form' %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Arts</h1>

<table class="table table-striped">

  <tbody>
    <% @arts.each do |art| %>
      <tr>
        <td>
         <div class= "image"> 
             <%= link_to (image_tag art.url, :style => "height:100px;width:150px"), art %>
         </div>
        </td>
        <td>
          <table>
            <tr>
              <td class="item-details-title">
              	<div class="name">
              	  <label>Name: </label>
              	</div>
            	</td>
            	<td class="item-details-description">	<%= art.name %> </td>
          	</tr>
          	<tr>
          	  <td class="item-details-title">
              	<div class="description">
                  <label>Description: </label>
              	</div>
            	</td>
            	<td class="item-details-description"><%= art.description %></td>
          	</tr>
          	<tr>
          	  <td class="item-details-title">
              	<div class="catagory">
              	  <label>Catagory: </label>
              	</div>
          	  </td>
          	  <td class="item-details-description"><%= art.catagory %></td>
          	</tr>
          	<tr>
          	  <td class="item-details-title">
              	<div class="size">
              	  <label>Size: </label>
              	</div>
              </td>
              <td class="item-details-description"><%= art.size %></td>
          	</tr>
          	<tr>
          	  <td class="item-details-title">
              	<div class ="price">
              	  <label>Price: </label>
              	</div>
               </td>
               <td class="item-details-description"> &#8364; <%= art.price %></td>
          	</tr>
        	</table>
          
          <div class="links">
            <% if current_user && current_user.admin? %>
              <%= link_to 'Edit', edit_art_path(art) %> |
              <%= link_to 'Delete', art, :data => {:confirm => 'Are you sure?'}, :method => :delete %>|
              <%= link_to 'Show', art, class: "action-link action-link-first" %>
            <% else %>
              <a href="/cart/<%= art.id %>">Add to Cart</a><br><br>
            <% end %>
          </div>
       
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>
 
<br>

<%= link_to 'New Art', new_art_path %>

app/views/arts/new.html.erb
<h1>New Art</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Art:</strong>
  <%= @art.art_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @art.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @art.description %>
</p>

<p>
  <strong>Catagory:</strong>
  <%= @art.catagory %>
</p>

<p>
  <strong>Size:</strong>
  <%= @art.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @art.price %>
</p>

<p>
  <strong>Url:</strong>
    <%= @art.url %>
</p>
<p>
   <%= link_to (image_tag @art.url, :style => "height:300px;width:400px;"), @art %>
</p>
<%= link_to 'Edit', edit_art_path(@art) %> |
<%= link_to 'Back', arts_path %>
<a href="/cart/<%= @art.id %>">Add to Cart</a>